[tool.poetry]
name = "rag"
version = "0.1.0"
description = ""
authors = ["vaaghu <vaaghu0@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
chromadb = "^0.4.24"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
